// <auto-generated />
using System;
using CafeMenu.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CafeMenu.Api.Migrations
{
    [DbContext(typeof(CafeMenuDbContext))]
    [Migration("20260809143638_CreateCafeThemeSchema")]
    partial class CreateCafeThemeSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CafeMenu.Api.Entities.AppUserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uk_app_user_email");

                    b.ToTable("app_user", "public");
                });

            modelBuilder.Entity("CafeMenu.Api.Entities.CafeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<string>("LogoImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cafe");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uk_cafe_slug");

                    b.ToTable("cafe", "public");
                });

            modelBuilder.Entity("CafeMenu.Api.Entities.CafeMembershipEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("app_user_id");

                    b.Property<long>("CafeId")
                        .HasColumnType("bigint")
                        .HasColumnName("cafe_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cafe_membership");

                    b.HasIndex("CafeId")
                        .HasDatabaseName("idx_cafe_membership_cafe");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("idx_cafe_membership_role");

                    b.HasIndex("AppUserId", "CafeId")
                        .IsUnique()
                        .HasDatabaseName("uk_cafe_membership_app_user_cafe_active")
                        .HasFilter("is_active = true AND is_deleted = false");

                    b.ToTable("cafe_membership", "public");
                });

            modelBuilder.Entity("CafeMenu.Api.Entities.CafeThemeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#D97706")
                        .HasColumnName("accent_color");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#FFFFFF")
                        .HasColumnName("background_color");

                    b.Property<long>("CafeId")
                        .HasColumnType("bigint")
                        .HasColumnName("cafe_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FontPreset")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("SYSTEM")
                        .HasColumnName("font_preset");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#111827")
                        .HasColumnName("primary_color");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#F9FAFB")
                        .HasColumnName("secondary_color");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#111827")
                        .HasColumnName("text_color");

                    b.Property<string>("ThemePreset")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("CLASSIC")
                        .HasColumnName("theme_preset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WelcomeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("welcome_description");

                    b.Property<string>("WelcomeTitle")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("welcome_title");

                    b.HasKey("Id")
                        .HasName("pk_cafe_theme");

                    b.HasIndex("CafeId")
                        .IsUnique()
                        .HasDatabaseName("uk_cafe_theme_cafe");

                    b.ToTable("cafe_theme", "public");
                });

            modelBuilder.Entity("CafeMenu.Api.Entities.CategoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CafeId")
                        .HasColumnType("bigint")
                        .HasColumnName("cafe_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasAlternateKey("CafeId", "Id")
                        .HasName("uk_category_cafe_id");

                    b.HasIndex("CafeId")
                        .HasDatabaseName("idx_category_cafe");

                    b.HasIndex("CafeId", "DisplayOrder")
                        .HasDatabaseName("idx_category_cafe_display_order");

                    b.ToTable("category", "public");
                });

            modelBuilder.Entity("CafeMenu.Api.Entities.ProductEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CafeId")
                        .HasColumnType("bigint")
                        .HasColumnName("cafe_id");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("CafeId")
                        .HasDatabaseName("idx_product_cafe");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_product_category");

                    b.HasIndex("CafeId", "CategoryId")
                        .HasDatabaseName("idx_product_cafe_category");

                    b.HasIndex("CafeId", "CategoryId", "DisplayOrder")
                        .HasDatabaseName("idx_product_cafe_category_display_order");

                    b.ToTable("product", "public");
                });

            modelBuilder.Entity("CafeMenu.Api.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("app_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("AppUserId")
                        .HasDatabaseName("idx_refresh_token_app_user");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uk_refresh_token_token_hash");

                    b.ToTable("refresh_token", "public");
                });

            modelBuilder.Entity("CafeMenu.Api.Entities.RoleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uk_role_code");

                    b.ToTable("role", "public");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "PLATFORM_ADMIN",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Manages platform-level administration.",
                            Name = "Platform Administrator",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2L,
                            Code = "CAFE_OWNER",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Cafe-scoped owner role reserved for membership authorization.",
                            Name = "Cafe Owner",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3L,
                            Code = "CAFE_MANAGER",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Cafe-scoped manager role reserved for membership authorization.",
                            Name = "Cafe Manager",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("app_user_role", b =>
                {
                    b.Property<long>("app_user_id")
                        .HasColumnType("bigint");

                    b.Property<long>("role_id")
                        .HasColumnType("bigint");

                    b.HasKey("app_user_id", "role_id")
                        .HasName("pk_app_user_role");

                    b.HasIndex("app_user_id")
                        .HasDatabaseName("idx_app_user_role_app_user");

                    b.HasIndex("role_id")
                        .HasDatabaseName("idx_app_user_role_role");

                    b.ToTable("app_user_role", "public");
                });

            modelBuilder.Entity("CafeMenu.Api.Entities.CafeMembershipEntity", b =>
                {
                    b.HasOne("CafeMenu.Api.Entities.AppUserEntity", "AppUser")
                        .WithMany("CafeMemberships")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cafe_membership_app_user");

                    b.HasOne("CafeMenu.Api.Entities.CafeEntity", "Cafe")
                        .WithMany("Memberships")
                        .HasForeignKey("CafeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cafe_membership_cafe");

                    b.HasOne("CafeMenu.Api.Entities.RoleEntity", "Role")
                        .WithMany("CafeMemberships")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cafe_membership_role");

                    b.Navigation("AppUser");

                    b.Navigation("Cafe");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CafeMenu.Api.Entities.CafeThemeEntity", b =>
                {
                    b.HasOne("CafeMenu.Api.Entities.CafeEntity", "Cafe")
                        .WithOne("Theme")
                        .HasForeignKey("CafeMenu.Api.Entities.CafeThemeEntity", "CafeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cafe_theme_cafe");

                    b.Navigation("Cafe");
                });

            modelBuilder.Entity("CafeMenu.Api.Entities.CategoryEntity", b =>
                {
                    b.HasOne("CafeMenu.Api.Entities.CafeEntity", "Cafe")
                        .WithMany("Categories")
                        .HasForeignKey("CafeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_cafe");

                    b.Navigation("Cafe");
                });

            modelBuilder.Entity("CafeMenu.Api.Entities.ProductEntity", b =>
                {
                    b.HasOne("CafeMenu.Api.Entities.CafeEntity", "Cafe")
                        .WithMany("Products")
                        .HasForeignKey("CafeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_cafe");

                    b.HasOne("CafeMenu.Api.Entities.CategoryEntity", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CafeId", "CategoryId")
                        .HasPrincipalKey("CafeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_category_cafe");

                    b.Navigation("Cafe");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CafeMenu.Api.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("CafeMenu.Api.Entities.AppUserEntity", "AppUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_app_user");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("app_user_role", b =>
                {
                    b.HasOne("CafeMenu.Api.Entities.AppUserEntity", null)
                        .WithMany()
                        .HasForeignKey("app_user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_user_role_app_user");

                    b.HasOne("CafeMenu.Api.Entities.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_user_role_role");
                });

            modelBuilder.Entity("CafeMenu.Api.Entities.AppUserEntity", b =>
                {
                    b.Navigation("CafeMemberships");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("CafeMenu.Api.Entities.CafeEntity", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Memberships");

                    b.Navigation("Products");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("CafeMenu.Api.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CafeMenu.Api.Entities.RoleEntity", b =>
                {
                    b.Navigation("CafeMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
